spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shopflow_users
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Bhuv@n2002

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
